// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: itcoursee/protocol/vo/courseware.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 课件
type Courseware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编号
	// @inject_tag: json:"id,string"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 拥有者编号，可能是
	// 课程
	// 讲次
	// @inject_tag: json:"ownerId,string,omitempty"
	OwnerId int64 `protobuf:"varint,10,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// 类型
	Type int32 `protobuf:"varint,20,opt,name=type,proto3" json:"type,omitempty"`
	// 子类型
	Subtype int32 `protobuf:"varint,21,opt,name=subtype,proto3" json:"subtype,omitempty"`
	// 名称
	Name string `protobuf:"bytes,30,opt,name=name,proto3" json:"name,omitempty"`
	// 状态
	Status int32 `protobuf:"varint,40,opt,name=status,proto3" json:"status,omitempty"`
	// 文件地址
	File string `protobuf:"bytes,50,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *Courseware) Reset() {
	*x = Courseware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itcoursee_protocol_vo_courseware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Courseware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courseware) ProtoMessage() {}

func (x *Courseware) ProtoReflect() protoreflect.Message {
	mi := &file_itcoursee_protocol_vo_courseware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courseware.ProtoReflect.Descriptor instead.
func (*Courseware) Descriptor() ([]byte, []int) {
	return file_itcoursee_protocol_vo_courseware_proto_rawDescGZIP(), []int{0}
}

func (x *Courseware) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Courseware) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Courseware) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Courseware) GetSubtype() int32 {
	if x != nil {
		return x.Subtype
	}
	return 0
}

func (x *Courseware) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Courseware) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Courseware) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_itcoursee_protocol_vo_courseware_proto protoreflect.FileDescriptor

var file_itcoursee_protocol_vo_courseware_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x6f, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa5, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x77, 0x61, 0x72, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x32, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x42, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e,
	0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x50, 0x01, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x6f, 0x3b, 0x76, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itcoursee_protocol_vo_courseware_proto_rawDescOnce sync.Once
	file_itcoursee_protocol_vo_courseware_proto_rawDescData = file_itcoursee_protocol_vo_courseware_proto_rawDesc
)

func file_itcoursee_protocol_vo_courseware_proto_rawDescGZIP() []byte {
	file_itcoursee_protocol_vo_courseware_proto_rawDescOnce.Do(func() {
		file_itcoursee_protocol_vo_courseware_proto_rawDescData = protoimpl.X.CompressGZIP(file_itcoursee_protocol_vo_courseware_proto_rawDescData)
	})
	return file_itcoursee_protocol_vo_courseware_proto_rawDescData
}

var file_itcoursee_protocol_vo_courseware_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_itcoursee_protocol_vo_courseware_proto_goTypes = []interface{}{
	(*Courseware)(nil), // 0: itcoursee.protocol.vo.Courseware
}
var file_itcoursee_protocol_vo_courseware_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_itcoursee_protocol_vo_courseware_proto_init() }
func file_itcoursee_protocol_vo_courseware_proto_init() {
	if File_itcoursee_protocol_vo_courseware_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_itcoursee_protocol_vo_courseware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Courseware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itcoursee_protocol_vo_courseware_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itcoursee_protocol_vo_courseware_proto_goTypes,
		DependencyIndexes: file_itcoursee_protocol_vo_courseware_proto_depIdxs,
		MessageInfos:      file_itcoursee_protocol_vo_courseware_proto_msgTypes,
	}.Build()
	File_itcoursee_protocol_vo_courseware_proto = out.File
	file_itcoursee_protocol_vo_courseware_proto_rawDesc = nil
	file_itcoursee_protocol_vo_courseware_proto_goTypes = nil
	file_itcoursee_protocol_vo_courseware_proto_depIdxs = nil
}
