// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: com/itcoursee/protocol/audit.proto

/*
Package protocol is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package protocol

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"github.com/itcoursee/core/audit"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_Audit_GetsByReview_0(ctx context.Context, marshaler runtime.Marshaler, client AuditClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq audit.GetsByReviewReq
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := client.GetsByReview(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_Audit_GetsByReview_0(ctx context.Context, marshaler runtime.Marshaler, server AuditServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq audit.GetsByReviewReq
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := server.GetsByReview(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterAuditHandlerServer registers the http handlers for service Audit to "mux".
// UnaryRPC     :call AuditServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterAuditHandlerFromEndpoint instead.
func RegisterAuditHandlerServer(ctx context.Context, mux *runtime.ServeMux, server AuditServer) error {

	mux.Handle("GET", pattern_Audit_GetsByReview_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/com.itcoursee.protocol.Audit/GetsByReview", runtime.WithHTTPPathPattern("/reviews/{id}/audits"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Audit_GetsByReview_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Audit_GetsByReview_0(annotatedContext, mux, outboundMarshaler, w, req, response_Audit_GetsByReview_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterAuditHandlerFromEndpoint is same as RegisterAuditHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterAuditHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterAuditHandler(ctx, mux, conn)
}

// RegisterAuditHandler registers the http handlers for service Audit to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterAuditHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterAuditHandlerClient(ctx, mux, NewAuditClient(conn))
}

// RegisterAuditHandlerClient registers the http handlers for service Audit
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "AuditClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "AuditClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "AuditClient" to call the correct interceptors.
func RegisterAuditHandlerClient(ctx context.Context, mux *runtime.ServeMux, client AuditClient) error {

	mux.Handle("GET", pattern_Audit_GetsByReview_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/com.itcoursee.protocol.Audit/GetsByReview", runtime.WithHTTPPathPattern("/reviews/{id}/audits"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Audit_GetsByReview_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Audit_GetsByReview_0(annotatedContext, mux, outboundMarshaler, w, req, response_Audit_GetsByReview_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

type response_Audit_GetsByReview_0 struct {
	proto.Message
}

func (m response_Audit_GetsByReview_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*audit.GetsByReviewRsp)
	return response.Audits
}

var (
	pattern_Audit_GetsByReview_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1, 2, 2}, []string{"reviews", "id", "audits"}, ""))
)

var (
	forward_Audit_GetsByReview_0 = runtime.ForwardResponseMessage
)
